server:
  port: 12315
spring:
  profiles:
    active: dev
  freemarker:
    check-template-location: false
  main:
    allow-circular-references: true
  cache:
    redis:
      time-to-live: 1800000
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:dd
    time-zone: GMT+8
    parser:
      allow-unquoted-control-chars: true
      allow-backslash-escaping-any-character: true
  jpa:
    open-in-view: false

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapping.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feishu-config:
  app-id: mpw:XmOtdJZ/rrM7t+S1c9SV2nyu+ihCGM3sSfkWWWcW/TY=
  app-secret: mpw:1HSZ98TVPJZoFZr0aHkbIv+jIxmu1niV5I8bhkDtSe/ENC5S07lLG1LKoKhOAkyr
  weekly-report-token: wikcnXpXCgmL3E7vdbM1TiwXiGc
  weekly-report-spaceId: 7046680616087126018