server:
  port: 12315
# 数据源
spring:
  profiles:
    active: dev
  freemarker:
    check-template-location: false
  main:
    allow-circular-references: true
  cache:
    redis:
      time-to-live: 1800000
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:dd
    time-zone: GMT-8
    parser:
      allow-unquoted-control-chars: true
      allow-backslash-escaping-any-character: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: mpw:Jrfx9m/vVYtI1PLKUIeYlA==
    password: mpw:tZLGHiKWlhtIyjhAlDJgQw==
    url: mpw:YAU7VUQTQlBTP/D7DYdMI5A5u1zqyh85JI/hVpPjrLzCpZnihi+gruSUQTzq8hl9p8mY2czOCrvHMrNNn5hE2869zSbitJStXAKwXQKs6yzl2JhuHSDinw5IyD2v7td4WFtaEQNW8VYwfi1CT17S4/Zf44Yht4Y0Pm/gaRPgSokkAa2s5qe1tu3m1oF4nCFiWsPOwe2hWdR6b6hI5L1Dca0CZCVTVW4dBM+ceuRmoEHR68ILnwSrc+jk7STgvjU+aQ3O/dFxmN7D2qLattxa5wEJjr9Xg5hxczIrC75/SBfst0IOmzqpQdgOyplnL6VGc7KZmcqxKunLwVhdNZqpCQ==
    hikari:
      connection-timeout: 30000     # 等待连接池分配链接的最大时长（毫秒），超过这个时长还没有可用的连接则发生 SQLException，默认：30 秒
      minimum-idle: 2               # 最小空闲连接数
      maximum-pool-size: 10         # 最大连接数
      auto-commit: true             # 自动提交
      idle-timeout: 600000          # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
      max-lifetime: 1800000         # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认： 30 分钟
      connection-test-query: SELECT 1
      pool-name: MakuHikariCP_Reminder
  jpa:
    open-in-view: false

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapping.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feishu-config:
  app-id: mpw:XmOtdJZ/rrM7t+S1c9SV2nyu+ihCGM3sSfkWWWcW/TY=
  app-secret: mpw:1HSZ98TVPJZoFZr0aHkbIv+jIxmu1niV5I8bhkDtSe/ENC5S07lLG1LKoKhOAkyr