server:
  port: 12315
# 数据源
spring:
  task:
    scheduling:
      pool:
        size: 5
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1/reminder?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
#      username: root
#      password: root
      url: mpw:jPBHDuoMjNCO2hqejmzo603OeDsMZH/FiReamKKNdUtzqKU1Z08e40JdMX6sl3dg5ukZfWYrartEzxqvRiNG/BzfPKug7Tt9oybgO1WSpXupXKON5oZD616f8d6uOJ3Upb4cR8aY2kIDDP1c5pQ883/IVXPQjqFLVBE9OjH5W+AiP541qXhKm6pfnSNjexZas8ItLbdaFKmwgg1qU/PsGoTrPTVtt/kvwmG6uWqxyWoxEnrFNy8gxOBvS5MhYylw+J4l954s1Xm1ix3gIzcYAspnnGd9J1lRbXlClm/iaDFEU0+Bouuqxz917w0CICzwlWmdaVjo1LeaADtYhi0+jw==
      username: mpw:Jrfx9m/vVYtI1PLKUIeYlA==
      password: mpw:Jrfx9m/vVYtI1PLKUIeYlA==
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      db-type: mysql

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapping.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  id: mpw:XmOtdJZ/rrM7t+S1c9SV2nyu+ihCGM3sSfkWWWcW/TY=
  secret: mpw:1HSZ98TVPJZoFZr0aHkbIv+jIxmu1niV5I8bhkDtSe/ENC5S07lLG1LKoKhOAkyr

redmine-config:
  api-access-key:
    saiko: 1f905383da4f783bad92e22f430c7db0b15ae258
  old_url: http://redmine-qa.mxnavi.com
